### ISSUE TITLE
Support ARM Images?

### ISSUE THREAD

**Issue by kferrone** [kubernetes-csi/node-driver-registrar#119]
I recently opened a request with `kubernetes-csi/csi-driver-smb` to support ARM. They did and pushed the image. Now this project needs the same. 
Here are the related issues and PRs:
 - https://github.com/kubernetes-csi/csi-driver-smb/issues/138#event-3978326534
 - https://github.com/kubernetes-csi/csi-driver-smb/pull/144

My end goal is to use the chart within smb-csi repo which also uses this projects image.

**Comment by msau42** [comment]
Try the latest 2.0.1 image on k8s.gcr.io

**Comment by kferrone** [comment]
I have it all up and running. Thank you.

**Comment by msau42** [comment]
Great!

/close
