### ISSUE TITLE
support JSON log format for node-driver-registrar

### ISSUE THREAD

**Issue by aramase** [kubernetes-csi/node-driver-registrar#128]
- Provide a flag to enable JSON log formatting. 

We do this today for CSI driver implementations but the same can't be configured for `node-driver-registrar`. This can be done by adding `log-format-json=true` flag to the node-driver-registrar and setting the log format based on that.

**Comment by serathius** [comment]
Hey, author of json format here.
It's great to see other components adopting structured logging and new format. Feel free to send PR review and feedback my way. I would be happy to remove any blockers and inconveniences in the current solution.
