### ISSUE TITLE
No Windows 2004 image available

### ISSUE THREAD

**Issue by quickstar** [kubernetes-csi/node-driver-registrar#135]
Hi

According to `curl -L https://mcr.microsoft.com/v2/oss/kubernetes-csi/csi-node-driver-registrar/tags/list` there is no image other than the 1809 kernel for Windows available.

It would make sense to support the versions according to the official [windows-os-version-support](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support)

**Comment by djboris9** [comment]
I've hand-built an image as a workaround for Win 2004: [djboris/node-driver-registrar:v2.1.0-7-g017ba7b8-2004](https://hub.docker.com/repository/docker/djboris/node-driver-registrar)

**Comment by js-rwwa** [comment]
Any update on this? Ive just run into the same issue using eksctl with Windows Node Group support, noticed there still isn't a 2004 image.

**Comment by msau42** [comment]
@mauriciopoppe can you confirm if 2004 images are published yet?

**Comment by msau42** [comment]
cc @jingxu97

**Comment by jingxu97** [comment]
they are available at gcr.io/gke-release/csi-node-driver-registrar:v2.2.0-gke.0

**Comment by msau42** [comment]
@jingxu97 since this is a community project we should be pushing the images to the k8s.gcr.io community repo.

**Comment by jingxu97** [comment]
oh, community repo k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0

**Comment by msau42** [comment]
Thanks!
/close

**Comment by mauriciopoppe** [comment]
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0 was released on April 22 however the changes I did were on May https://github.com/kubernetes-csi/node-driver-registrar/pull/147/files, I think we need to verify that the docker manifest for v2.2.0 has all the windows versions

/reopen
/assign

**Comment by mauriciopoppe** [comment]
I've verified that the https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.3.0 of node-driver-registrar (available through k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0) includes an image for 2004.

- I copied k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0 to my repo
- I checked that the manifest has the 2004 windows version

```
❯ docker manifest inspect gcr.io/my-repo/csi-node-driver-registrar:v2.3.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:7c601d4033670365dd25578f3f5c655e33938360d4ae89651d8ac6f69157f9d2",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 950,
         "digest": "sha256:d3da39505e65f08131b60dacac22b4a3a1be912df763f7c98b053de19b3bb322",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.2114"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 950,
         "digest": "sha256:86f433c588aaacb71d633fcb8f88d3f67473bfeb066e552120af3587dc802252",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.18363.1556"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 950,
         "digest": "sha256:da53d8f7b69ec221a8c53e2856a30c717d4fb41303e4071f612d88fc591668d1",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19041.1165"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 950,
         "digest": "sha256:07b35ae4b3f0f53740018a7cb5730ec5de33b3c1b7c4c4af34640c45377bd9db",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19042.1165"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:11b414474d388fd6e650d08f104f1a4ff43201bada765b8af25d9b489b240edf",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:a6b3d3f136ab80eefe591c113946d50f2b37d9753562ce5572fea8ed521bb9d0",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:60e33344d8a476983a59a2c0ae89b5c0c3b5260ee0428c87b9539b267c309057",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

I've also checked that the testgrid links for the windows distros where GCE PD CSI Driver runs are green, see https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/828#issuecomment-906563003

/close
