### ISSUE TITLE
update the windows dockerfile to use a relative path to binary for better host process support

### ISSUE THREAD

**Issue by travisghansen** [kubernetes-csi/node-driver-registrar#200]
When using windows host process containers the entrypoint needs to be relative otherwise it looks for the binary at that path on the actual host filesystem.

**Comment by travisghansen** [comment]
Not stale.

**Comment by mauriciopoppe** [comment]
For a HostProcess container we have tried expressing the path absolutely with respect to the host and that has worked fine in the experiments https://github.com/kubernetes-csi/csi-proxy/blob/library-development/docs/USAGE.md, I think that there's this special env var `CONTAINER_SANDBOX_MOUNT_POINT` where the container will be created pointing to a directory that is the filesystem root in the container.

I think that expressing the path absolute with respect to the host works for us, we could add more documentations for it on the node-driver-registrar README, thoughts?
