### ISSUE TITLE
remove reg.sock on shutdown

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/node-driver-registrar#21]
When driver-registrar terminates, it should ensure that it removes the `*-reg.socket` file that it created. It will get overwritten when restarting, but when experimenting with different drivers or testing with driver renaming, those files accumulate under `/var/lib/kubelet/plugins/` and then plugin registration in kubelet gets slower (several minutes!). That might be something worth fixing in kubelet (not sure?), but either way it is better to clean up.

Not much can be done when the registrar gets killed with SIGKILL or crashes, but hopefully that'll be rare.

This is something I've seen with driver-registrar 0.4.1, but probably still applies.

**Comment by pohly** [comment]
That sounds like a good approach. I think it should be described in the documentation of node-driver-registrar. We can use this issue to track that.

**Comment by mlmhl** [comment]
@msau42 Currently we use `gcr.io/distroless/static:latest` as the base image, and it doesn't have a `sh` command, so the [pre stop hook](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/base/node.yaml#L26) always failed. Do we have a better way to do this?

**Comment by msau42** [comment]
I was incorrect in my earlier assumption that prestop hook handles ungraceful cases.  I think it execs into the container so it requires the container to be running.  So, considering that the prestop hook only handled graceful cases anyway, what if we add a sigterm handler to the node driver registrar?

**Comment by davidz627** [comment]
>  what if we add a sigterm handler to the node driver registrar?

+1

**Comment by lancelot1989** [comment]
this is an essential feature for registrar, which completes the lifecycle

**Comment by paullaffitte** [comment]
I found quite unclear to know whether this bug has been addressed or not.
