### ISSUE TITLE
I‘d like to understand your release strategy

### ISSUE THREAD

**Issue by MobsMao** [kubernetes-csi/node-driver-registrar#226]
Since last release is released in May, and many CVE mitigation PRs has been merged. But how often would you release a new version of node-driver-registrar? Like when we can get a newly release that contains the fixes?
Thank you!

**Comment by mauriciopoppe** [comment]
I answered a similar question in livenessprobe in https://github.com/kubernetes-csi/livenessprobe/issues/163, we try to have a release for every kubernetes release and we were missing one for the 1.25 release.

We released v2.6.0, I checked that it's available with `docker pull k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.0`
