### ISSUE TITLE
High risk vulnerability with v2.7.0

### ISSUE THREAD

**Issue by bbindela** [kubernetes-csi/node-driver-registrar#292]
Hi Team,

We have one High risk vunerability with v2.7.0

golang.org/x/net version v0.4.0 has 1 vulnerability

<img width="922" alt="image" src="https://user-images.githubusercontent.com/103967618/234647512-9fd5ee50-91d0-4207-92a9-986ecf8abe24.png">

Can you please help us by fixing this.
With this, node-driver-registrar will be vulnerability free.

Thank you.

**Comment by liangyuanpeng** [comment]
It's possible update the node-driver-registrar version?

**Comment by jsafrane** [comment]
/close
This has been fixed since v2.8.0 that has golang.org/x/net v0.8.0

Since CVE patching is done manually by volunteers, we strongly prefer PRs instead of issues.
