### ISSUE TITLE
Unnecessary write to root filesystem

### ISSUE THREAD

**Issue by mattcary** [kubernetes-csi/node-driver-registrar#315]
cmd/main.go:GetInfo writes to registrationProbePath, even when --mode=registration. But kubelet-registration-path refers to /var/lib/kubelet, which is not mounted into the registrar container in --mode=registration.

/assign @mattcary

**Comment by mauriciopoppe** [comment]
This is related to https://github.com/kubernetes-csi/node-driver-registrar/issues/309, I wrote some strategies there about how to make it work by making the --mode=kubelet-registration-info always return exit code 0 and removing all the other supporting code including the unnecessary write to the root fs.

**Comment by mattcary** [comment]
I think it is not correct to use --kubelet-registration-path in mode=registration, as it's a container local path and not actually /var/lib/kubelet. So we should be able to make that change immediately? Let me start a PR to be concrete about what I mean.

@jsafrane

**Comment by mauriciopoppe** [comment]
yes, we can do the changes for #309 immediately i.e. https://github.com/kubernetes-csi/node-driver-registrar/issues/309#issuecomment-1606178000

**Comment by mattcary** [comment]
Oh, I see what you mean. Thanks for clarifying. I'll do that.

**Comment by mauriciopoppe** [comment]
#316 implemented https://github.com/kubernetes-csi/node-driver-registrar/issues/315#issuecomment-1646058503. With the new release the write no longer to the root filesystem no longer happens.
