### ISSUE TITLE
runnung on kubernetes 1.12.x

### ISSUE THREAD

**Issue by muecahit94** [kubernetes-csi/node-driver-registrar#32]
Hi,
is there a way to use this on kubernetes 1.12.x?

I use Rancher and the stable version supports only k8s 1.12.x versions.
I tried to setup GCS, everything works, but when i want to assign a PVC to a workload, it throws this issue:

```
MountVolume.MountDevice failed for volume "pvc-bad5e7b6-2fb1-11e9-aac6-002590927952" : driver name org.gluster.glusterfs not found in the list of registered CSI drivers
```

Pls give me some tips if its possible to use is on kubernetes 1.12.x

**Comment by msau42** [comment]
Hi @muecahit94, the node-driver-registrar only works with CSI Spec 1.0 which is not supported in Kubernetes 1.12.  For an example on how to use the driver-registrar in 1.12, you can look at the example specs we used for e2e testing: https://github.com/kubernetes/kubernetes/tree/release-1.12/test/e2e/testing-manifests/storage-csi/gce-pd
