### ISSUE TITLE
Discover CSI spec version

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/node-driver-registrar#35]
Right now the node-driver-registrar hardcodes the CSI spec version supported from the driver.

Ideally, this should be discovered from the plugin's RPC service version.  If that's not possible, then we should consider using GetPluginInfo() to pass this information through.

cc @saad-ali @jsafrane

**Comment by jsafrane** [comment]
I checked current CSI spec and there is no call where a driver would report CSI versions it supports.  `vendor_version` is IMO version of the driver, not version of the protocol. Resizing should depend on presence of `EXPAND_VOLUME` capability.

**Comment by msau42** [comment]
Discussed this more with @jsafrane and we don't think there's a great way to automatically do this.  grpc does have support for reflection of the exported services and their methods, but it's optional so not all drivers will support it.  Also the service names for CSI just say "v1" for both 1.0 and 1.1 specs.

/close
