### ISSUE TITLE
need version compatibility for windows 2022

### ISSUE THREAD

**Issue by thdrnsdk** [kubernetes-csi/node-driver-registrar#377]
in the repo dockerfile.windows
there is base, addon image is windwos images "1809"

Images created in this way do not seem to work on Windows 2022 servers due to version compatibility issues.

**Comment by mauriciopoppe** [comment]
Please look at this answer https://github.com/kubernetes-csi/livenessprobe/issues/243, it's also applicable for node-driver-registrar
