### ISSUE TITLE
Supported version streams? 

### ISSUE THREAD

**Issue by mamccorm** [kubernetes-csi/node-driver-registrar#395]
Hi there. Hoping to clear up some confusion re: which versions are actively supported. Re the docs:
 - https://kubernetes-csi.github.io/docs/node-driver-registrar.html
 
 Implies that v6 - v9 are supported, but the last release tag cut for v6 was back in January 2023, and for v2.7 was December 2022. Also theres no mention of v10 in the docs.

Be great if you could confirm what are the active releases you currently support (i.e maintain with updates). Thanks in advance

**Comment by captn3m0** [comment]
The page is also missing the newer releases: 2.10, and 2.11.

We are currently marking 6-11 as supported at https://endoflife.date/kubernetes-csi-node-driver-registrar, but it is confusing.

**Comment by captn3m0** [comment]
@mamccorm could you re-open this please? https://kubernetes-csi.github.io/docs/node-driver-registrar.html hasn't been updated in a year now.
