### ISSUE TITLE
Feature request: implement a readiness probe

### ISSUE THREAD

**Issue by okartau** [kubernetes-csi/node-driver-registrar#41]
- implement a readiness probe for the sidecar
- return "ready" only once connected to the driver

Background: we debugged a [pmem-csi](https://github.com/intel/pmem-CSI) deployment case where node-driver-registrar 1.0.2 failed to connect to /csi/csi.sock, getting timeout and causing pod exit in 60 seconds, leading to CrashLoop.
We then tried version 1.1.0 which does not timeout. There the pod remained running and gave false impression of good state, but in reality it kept trying socket connection which never succeeded. In that sense the v1.1.0 "try without timeout" semantics can be considered harmful as problem state remains hidden (if one does not look in log).

@pohly then expressed idea about readiness probe.

The deployment problem looked initially a lot like #36 (but SELinux was not involved) but got explained as missing /csi/csi.sock caused by chain starting with other misconfiguration, so nothing to blame as system functioned exactly the way it was configured.

**Comment by pohly** [comment]
We discussed this in the Kubernetes-CSI WG today. The conclusion was that this is worth looking into.

This probably can be implemented the same way for all sidecars using the csi-lib-utils connection code (return ready while connected) and the common code can be in that repo.

/cc @msau42 

/help

@okartau is that perhaps an issue that you want to work on as an upstream contribution?

**Comment by okartau** [comment]
> is that perhaps an issue that you want to work on

yes

**Comment by okartau** [comment]
@pohly to verify implementation idea:
- Sidecar container listens to a TCP socket (to be added) which serves as readiness probe receive point.
- A connection made there activates code in container (runs in independent thread as main code may be busy in Connect()) checking "is CSI unix-socket connected?", if yes => ready. This new check will be implemented in csi-lib-utils connection code.

or something else?

**Comment by pohly** [comment]
@okartau that sounds about right.
