### ISSUE TITLE
Liveness probe fails after upgrading to v2.11.0

### ISSUE THREAD

**Issue by peng225** [kubernetes-csi/node-driver-registrar#425]
We have recently upgraded the node-driver-registrar version for our own CSI driver (named [TopoLVM](https://github.com/topolvm/topolvm)) from v2.10.1 to v2.11.0. After that, our CSI node driver started to crash repeatedly.

The node driver crashed due to the node-driver-registrar's liveness probe failure. The events of our node driver pod and the node-driver-registrar's log are as follows:

Events:
```
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  BackOff    14m (x2131 over 16h)   kubelet  Back-off restarting failed container csi-registrar in pod topolvm-node-64bp7_topolvm-system(62fd14cf-4bac-4620-a06a-35d4f263394c)
  Warning  Unhealthy  3m11s (x567 over 16h)  kubelet  Liveness probe failed: HTTP probe failed with statuscode: 500
```

Logs:
```
I0709 01:51:24.640458       1 main.go:150] "Version" version=""
I0709 01:51:24.640542       1 main.go:151] "Running node-driver-registrar" mode=""
I0709 01:51:24.645664       1 node_register.go:56] "Starting Registration Server" socketPath="/registration/topolvm.cybozu.com-reg.sock"
I0709 01:51:24.645840       1 node_register.go:66] "Registration Server started" socketPath="/registration/topolvm.cybozu.com-reg.sock"
I0709 01:51:24.645940       1 node_register.go:99] "Starting HTTP server" endpoint=":9809"
I0709 01:51:26.356668       1 main.go:96] "Received GetInfo call" request="&InfoRequest{}"
I0709 01:51:26.377111       1 main.go:108] "Received NotifyRegistrationStatus call" status="&RegistrationStatus{PluginRegistered:true,Error:,}"
E0709 01:52:24.428521       1 node_register.go:111] "Health check failed" err="error connecting to node-registrar socket /registration/topolvm.cybozu.com-reg.sock: context deadline exceeded"
E0709 01:53:24.428963       1 node_register.go:111] "Health check failed" err="error connecting to node-registrar socket /registration/topolvm.cybozu.com-reg.sock: context deadline exceeded"
E0709 01:54:24.428199       1 node_register.go:111] "Health check failed" err="error connecting to node-registrar socket /registration/topolvm.cybozu.com-reg.sock: context deadline exceeded"
```

We investigated this issue and found that the following PR have changed the liveness probe behavior.
https://github.com/kubernetes-csi/node-driver-registrar/pull/406

Before merging this PR, the context variable `ctx` was not handed over from the upper function.
However, by the change of the PR, now the context with 1 sec timeout (which is the default value of `operationTimeout`) is handed over to `checkLiveRegistrationSocket` function. We suspect this change causes the liveness probe timeout.

We changed the timeout to 10 minutes using the `--timeout` option for investigation, and confirmed that the problem was resolved.

I wonder if the changes in the PR are intentional or a bug.

**Comment by jsafrane** [comment]
Good catch, I'm fixing it in #426.
