### ISSUE TITLE
Multi-Arch build

### ISSUE THREAD

**Issue by diederichm** [kubernetes-csi/node-driver-registrar#48]
Can you please build for s390x (and maybe ppc64 and ppc64le) ?

**Comment by ahuffman** [comment]
Any updates on getting a multi-arch build for this?

**Comment by msau42** [comment]
Work is in progress to migrate our build infrastructure to the build pipeline supported by wg-k8s-infra. Once we migrate there, then we can look into supporting multi-arch builds.

**Comment by edmondsw** [comment]
@msau42 Thanks for the update. What is the projected timeline for that migration?

**Comment by msau42** [comment]
It's being actively worked on as we speak. I would expect by next month we should have something.

Also for reference, here's the suggested arches to support initially:
https://github.com/kubernetes/kubernetes/blob/master/build/pause/Makefile#L36-L54

**Comment by msau42** [comment]
/assign @pohly @jingxu97 
cc @vitt-bagal

**Comment by edmondsw** [comment]
@msau42 excellent! Thank you!

**Comment by holdenk** [comment]
So I was also curious @ruckc it looks like the latest release does not yet have a multi-arch build. I ran `holden@hkdesktop:~/repos/scalingpythonml/make_k8s_cluster$ docker buildx imagetools inspect k8s.gcr.io/sig-storage/csi-node-driver-registrar:v1.3.0` and I got back:

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 2466,
      "digest": "sha256:37c1d9ea538b6139df2dc2807b565afed0bf47be2323ece2b83fa2d8f088ffe1"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 655317,
         "digest": "sha256:9ff2acc3204b4093126adab3fed72de8f7bbfe332255b199c30b8b185fcf6923"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 7058616,
         "digest": "sha256:d0bfaf7febc5bdba655bb83e6806ed72c9017ecef71ee98871eb0ee1ddd5fdb3"
      }
   ]
}

```

Does anyone know of v2.0 is planned to support multi-arch builds?

**Comment by pohly** [comment]
> Does anyone know of v2.0 is planned to support multi-arch builds?

Yes, they are. See https://github.com/kubernetes-csi/csi-release-tools/issues/86

**Comment by msau42** [comment]
This should be done as of v2.0

/close
