### ISSUE TITLE
Ensure reg.sock exists while the registrar is running

### ISSUE THREAD

**Issue by verult** [kubernetes-csi/node-driver-registrar#57]
While the registrar is running, the kubelet registration socket it installs could be removed erroneously by a different process (for example if two instances of the same driver are running in the cluster). The registrar should continuously ensure that the socket exists during its lifetime (and subsequently removed before it terminates).

/cc @davidz627 @msau42

**Comment by zhucan** [comment]
@verult if reg.sock not exists, we should create the socket？https://github.com/kubernetes-csi/node-driver-registrar/blob/204944afecf1fada1ed92d3acb8888f3573bb90b/cmd/csi-node-driver-registrar/node_register.go#L47

**Comment by verult** [comment]
That's what it does today - at initialization time, if socket doesn't exist, it'll create a socket. In addition to that, the registrar should *periodically* check whether the socket exists and create a new one if it doesn't

**Comment by msau42** [comment]
@chrishenzie is going to take a look at this
