### ISSUE TITLE
Upgrade grpc-go dependency to allow drivers to be written in rust / typescript

### ISSUE THREAD

**Issue by entropitor** [kubernetes-csi/node-driver-registrar#93]
Due to a bug in grpc-go, drivers in typescript / rust weren't working. This has been fixed so now this package needs to update its dependency on grpc-go soon (https://github.com/grpc/grpc-go/issues/2628)

**Comment by msau42** [comment]
From the issue it looks like this fix is going to be in grpc 1.31?
/help
/good-first-issue

**Comment by entropitor** [comment]
@Jiawei0227 Do we still need https://github.com/kubernetes/kubernetes/issues/93320 to be merged as well or should this be enough to start writing CSI's in other languages without any hacks?
