### ISSUE TITLE
FeatureRequest: Add support for configuring the registration socket path

### ISSUE THREAD

**Issue by SaranBalaji90** [kubernetes-csi/node-driver-registrar#94]
As per the current code we expect `/var/lib/kubelet/plugins_registry/` to be mounted as `/registration`. This works well when `node-driver-registrar` runs as sidecar container or as a pod. We have a usecase to run node-driver-registrar as systemd process to support csi driver for specific set of worker nodes (https://github.com/aws/containers-roadmap/issues/826). Therefore, instead of hardcoding `/registartion` would be helpful if we can read this value from a parameter. If the new parameter is empty then it can default to `/registration`

Would like to get community feedback on whether this is acceptable or is the node-driver-registrar designed to run only as side-car container?. if we decide to add new parameter then naming might be a difficult part I think, given that we already have parameter named `kubelet-registrataion-path` which points to csi socket path.

**Comment by msau42** [comment]
I think a parameter to configure it is fine. How about `plugin-registration-path` as a name?
